# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod 'Alamofire'
pod 'Kingfisher'

target 'DouYuZB' do

  # Pods for DouYuZB

  target 'DouYuZBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DouYuZBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
